name = "IRStructurizer"
uuid = "93e32bba-5bb8-402b-805d-ffb066edee93"
authors = ["Tim Besard <tim.besard@gmail.com>"]
version = "0.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
Graphs = "1.13.2"
