name = "IRStructurizer"
uuid = "93e32bba-5bb8-402b-805d-ffb066edee93"
authors = ["Tim Besard <tim.besard@gmail.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
AbstractTrees = "0.4"
Graphs = "1.13.2"
MLStyle = "0.4"
OrderedCollections = "1"
